services:
  - type: web
    name: fashion-store-frontend
    env: static
    rootDir: frontend
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    staticPublishPath: dist/fashion-store
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache 