[build]
command = "npm run build"
publish = "frontend/dist/fashion-store"

[build.environment]
NODE_VERSION = "18.19.0"

# Use this format for Cloudflare Pages
pages_build_output_dir = "frontend/dist/fashion-store" 